[package]

name = "music"
description = "Scaleless music."
version = "0.0.5"
authors = ["Tibor Gáts <tibor.gats@gmail.com>"]
readme = "README.md"
keywords = ["music", "sound", "audio"]
license = "WTFPL"
repository = "https://github.com/tiborgats/music"
homepage = ""
documentation = ""

[features]
default = ["be-portaudio"]
# Optional backends
be-portaudio = ["portaudio", "lazy_static"]
be-rsoundio = ["rsoundio", "rb"]

[dependencies]
portaudio = { version = "0.6.4", optional = true }
lazy_static = { version = "0.2.1", optional = true }
rsoundio = { version = "0.1.6", optional = true }
rb = { version = "0.2.0", optional = true }
num = "0.1.34"

[dev-dependencies]
piston_window = "*"
piston = "*"
glium = "*"
conrod = "*"
