[package]

name = "music"
version = "0.0.2"
authors = ["Tibor Gáts <tibor.gats@gmail.com>"]
description = "Scaleless music."
readme = "README.md"
keywords = ["music", "sound", "audio"]
license = "undecided"
repository = ""
homepage = ""

[dependencies]
portaudio = "*"
lazy_static = "*"
rayon = "*"
piston_window = "*"
piston = "*"
glium = "*"
conrod = "*"
