[package]
name = "scaleless_music"
description = "A library for building music with precise harmonies, without the limitations of any musical scale."
version = "0.0.6"
authors = ["Tibor Gáts <tibor.gats@gmail.com>"]
readme = "README.md"
keywords = ["music", "scaleless", "sound", "audio"]
license = "WTFPL"
repository = "https://github.com/tiborgats/scaleless_music"
documentation = "https://tiborgats.github.io/scaleless_music"

[features]
default = ["be-portaudio"]
# Optional backends
be-portaudio = ["portaudio"]
be-rsoundio = ["rsoundio", "rb"]

[dependencies]
portaudio = { version = "0.7.0", optional = true }
rsoundio = { version = "0.1.6", optional = true }
rb = { version = "0.2.0", optional = true }
num = "0.1.34"

[dev-dependencies]
piston_window = "0.51.1"
piston = "0.24.0"
conrod = "0.39.0"
