[package]

name = "music"
description = "Scaleless music."
version = "0.0.2"
authors = ["Tibor Gáts <tibor.gats@gmail.com>"]
readme = "README.md"
keywords = ["music", "sound", "audio"]
license = "undecided"
repository = "https://github.com/tiborgats/music"
homepage = ""
documentation = ""

[features]
default = ["portaudio"]

[dependencies]
portaudio = { version = "0.6.4", optional = true }
rsoundio = { version = "0.1.6", optional = true }
lazy_static = "0.2.1"
rayon = "0.4.0"

[dev-dependencies]
piston_window = "*"
piston = "*"
glium = "*"
conrod = "*"
